"""SpiderRock message inventory (58 mTyp) and 18 REST endpoint query shapes."""
from __future__ import annotations

# Verified from SPIDERROCK_MESSAGE_INVENTORY.csv (58 unique mTyp).
ALL58_MESSAGES: list[str] = [
    "AggregateCount",
    "AggregateNumeric",
    "AggregateString",
    "BucketRange",
    "EquityCorpActionRecordV5",
    "GlobalRates",
    "HistoricalVolatilities",
    "LiveAtmVol",
    "LiveImpliedQuote",
    "LiveImpliedQuoteAdj",
    "LiveImpliedQuoteDisp",
    "LiveSurfaceAtm",
    "LiveSurfaceCurve",
    "LiveSurfaceFixedGrid",
    "LiveSurfaceFixedTerm",
    "MLinkAdmin",
    "MLinkCount",
    "MLinkDataAck",
    "MLinkHeartbeat",
    "MLinkLogon",
    "MLinkSignalReady",
    "MLinkStream",
    "MLinkStreamAck",
    "MLinkStreamCheckPt",
    "MLinkSubscribe",
    "MLinkSubscribeAck",
    "MLinkSubscribeCheckPt",
    "MLinkTheoModel",
    "MsgExpiryKey",
    "MsgOptionKey",
    "MsgTickerKey",
    "OddLotBookQuote",
    "OpraPrintType",
    "OptExpiryDefinition",
    "OptionAtmMinuteBarSet",
    "OptionCloseMark",
    "OptionCorpActionRecordAdjV5",
    "OptionCorpActionRecordV5",
    "OptionMarketSummary",
    "OptionNbboQuote",
    "OptionOpenInterest",
    "OptionOpenMark",
    "OptionPrint",
    "OptionPrintSet",
    "OptionRiskFactor",
    "PostAck",
    "RootDefinition",
    "StockBeta",
    "StockBookQuote",
    "StockCloseMark",
    "StockMarketSummary",
    "StockMinuteBar",
    "StockOpenMark",
    "StockPrint",
    "TickerDefinition",
    "TickerItemDef",
    "UserApiKey",
    "UserMetaData",
]

# 18 endpoint shapes — rotate one per scheduled run.
# Placeholders: {message}, {ticker}
ENDPOINT_SHAPES: list[dict[str, str]] = [
    {"cmd": "getmsgs", "msgtype": "{message}", "ticker": "{ticker}"},
    {"cmd": "getmsgs", "msgName": "{message}", "ticker": "{ticker}"},
    {"cmd": "getmsgs", "msg": "{message}", "ticker": "{ticker}"},
    {"cmd": "getmsgs", "mTyp": "{message}", "ticker": "{ticker}"},
    {"cmd": "select", "msgtype": "{message}", "ticker": "{ticker}"},
    {"cmd": "select", "msgName": "{message}", "ticker": "{ticker}"},
    {"cmd": "select", "msg": "{message}", "ticker": "{ticker}"},
    {"cmd": "select", "mTyp": "{message}", "ticker": "{ticker}"},
    {"cmd": "getmsgs", "msgtype": "{message}", "ticker": "{ticker}", "view": "detail"},
    {"cmd": "getmsgs", "msgName": "{message}", "ticker": "{ticker}", "view": "detail"},
    {"cmd": "getmsgs", "mTyp": "{message}", "ticker": "{ticker}", "view": "detail"},
    {"cmd": "getmsgs", "msgtype": "{message}", "ticker": "{ticker}", "limit": "100"},
    {"cmd": "getmsgs", "msgName": "{message}", "ticker": "{ticker}", "limit": "100"},
    {"cmd": "getmsgs", "mTyp": "{message}", "ticker": "{ticker}", "limit": "100"},
    {"cmd": "getmsgs", "messageType": "{message}", "ticker": "{ticker}"},
    {"cmd": "getmsgs", "MessageType": "{message}", "ticker": "{ticker}"},
    {"cmd": "select", "msgtype": "{message}", "ticker": "{ticker}", "limit": "100"},
    {"cmd": "select", "mTyp": "{message}", "ticker": "{ticker}", "view": "detail"},
]
