name: Sniper Scanner Automation

on:
  schedule:
    - cron: "0 3 * * *" # Runs daily at 3:00 AM UTC
  workflow_dispatch: # Allows manual triggering from GitHub

jobs:
  run-sniper-scanner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Check Current Branch and Commit
        run: |
          echo "Current Branch and Commit:"
          git rev-parse HEAD
          git branch
          echo "Directory Listing:"
          ls -la

      - name: Install Dependencies
        run: |
          echo "Installing Dependencies..."
          pwd
          ls -la
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Run Sniper Scanner
        env:
          SNIPER_SPIDER_API_KEY: ${{ secrets.SNIPER_SPIDER_API_KEY }}
        run: python sniper_scanner/scanner.py